// ui-svelte/src/components/BodyPane.svelte
<script lang="ts">
  import type { BodyState } from "@ui/state/reducer";
  import { decodeBody, type DecodeResult } from "@ui/body/decode";
  import { formatSize } from "@ui/lib/utils";
  import CopyButton from "./CopyButton.svelte";
  import EmptyState from "./ui/EmptyState.svelte";
  import SectionHeader from "./ui/SectionHeader.svelte";
  import JsonViewer from "./JsonViewer.svelte";

  interface Props {
    title: string;
    body: BodyState | undefined;
  }

  const { title, body }: Props = $props();

  let loading = $state(false);
  let result = $state<DecodeResult | null>(null);

  $effect(() => {
    if (body == null || !body.atEnd) {
      loading = false;
      result = null;
      return;
    }

    loading = true;
    result = null;
    let cancelled = false;

    decodeBody(body)
      .then((r) => {
        if (!cancelled) {
          result = r;
          loading = false;
        }
      })
      .catch(() => {
        if (!cancelled) {
          result = null;
          loading = false;
        }
      });

    return () => {
      cancelled = true;
    };
  });

  const decodeFailed = $derived(
    !loading && body != null && body.atEnd && result == null,
  );
</script>

<div class="flex flex-col border border-border h-full overflow-hidden">
  <div
    class="flex items-center gap-3 px-3 h-7 shrink-0 bg-bg2 border-b border-border"
  >
    <SectionHeader>{title}</SectionHeader>
    {#if result != null}
      <span class="font-family-mono text-xs text-dim">{result.mediaType}</span>
    {/if}
    <div class="ml-auto flex items-center gap-2">
      {#if result != null}
        <span class="font-family-mono text-xs text-dim">
          {formatSize(result.size)}
        </span>
      {/if}
      {#if body != null}
        <CopyButton text={result?.text} />
      {/if}
    </div>
  </div>

  <div class="flex-1 overflow-auto bg-pane-bg">
    {#if loading}
      <EmptyState>Decoding…</EmptyState>
    {:else if body != null && !body.atEnd}
      <EmptyState>Streaming… ({formatSize(body.totalBytes)} received)</EmptyState>
    {:else if body == null}
      <EmptyState>No body</EmptyState>
    {:else if decodeFailed}
      <EmptyState>Decode failed</EmptyState>
    {:else if result != null && (result.kind === "json" || result.kind === "jsonl") && result.text != null}
      <JsonViewer text={result.text} />
    {:else if result != null && result.kind === "text" && result.text != null}
      <pre class="font-family-mono text-xs text-ink p-3 whitespace-pre-wrap"
        >{result.text}</pre
      >
    {:else if result != null && result.kind === "binary"}
      <EmptyState>Binary data · {formatSize(result.size)}</EmptyState>
    {/if}
  </div>
</div>

// ui/src/components/BodyPane.tsx
import { useEffect, useState } from "react";
import type { BodyState } from "@ui/state/reducer";
import { decodeBody, type DecodeResult } from "@ui/body/decode";
import { formatSize } from "@ui/lib/utils";
import { EmptyState } from "./ui/EmptyState";
import { SectionHeader } from "./ui/SectionHeader";
import { JsonViewer } from "./JsonViewer";

interface Props {
  title: string;
  body: BodyState | undefined;
}

type DecodeEntry =
  | { status: "done"; body: BodyState; result: DecodeResult }
  | { status: "failed"; body: BodyState };

function useDecodeBody(body: BodyState | undefined): {
  loading: boolean;
  result: DecodeResult | null;
} {
  const [entry, setEntry] = useState<DecodeEntry | null>(null);

  useEffect(() => {
    if (body == null || !body.atEnd) {
      return;
    }
    let cancelled = false;
    decodeBody(body)
      .then((r) => {
        if (!cancelled) {
          setEntry({ status: "done", body, result: r });
        }
      })
      .catch(() => {
        if (!cancelled) {
          setEntry({ status: "failed", body });
        }
      });
    return () => {
      cancelled = true;
    };
  }, [body]);

  if (body == null) return { loading: false, result: null };
  if (!body.atEnd) return { loading: false, result: null };

  // body.atEnd is true — either we have a completed entry for this body, or we're loading
  if (entry != null && entry.body === body) {
    return {
      loading: false,
      result: entry.status === "done" ? entry.result : null,
    };
  }
  return { loading: true, result: null };
}

export function BodyPane({ title, body }: Props) {
  const { loading, result } = useDecodeBody(body);

  return (
    <div className="flex flex-col border border-border h-full overflow-hidden">
      {/* Header row */}
      <div className="flex items-center gap-3 px-3 h-7 shrink-0 bg-bg2 border-b border-border">
        <SectionHeader>{title}</SectionHeader>
        {result != null && (
          <>
            <span className="font-family-mono text-xs text-dim">
              {result.mediaType}
            </span>
            <span className="font-family-mono text-xs text-dim ml-auto">
              {formatSize(result.size)}
            </span>
          </>
        )}
      </div>

      {/* Body area */}
      <div className="flex-1 overflow-auto bg-pane-bg">
        {loading && <EmptyState>Decoding…</EmptyState>}

        {!loading && body != null && !body.atEnd && (
          <EmptyState>
            Streaming… ({formatSize(body.totalBytes)} received)
          </EmptyState>
        )}

        {!loading && body == null && <EmptyState>No body</EmptyState>}

        {!loading && body != null && body.atEnd && result == null && (
          <EmptyState>Decode failed</EmptyState>
        )}

        {!loading &&
          result != null &&
          (result.kind === "json" || result.kind === "jsonl") &&
          result.text != null && <JsonViewer text={result.text} />}

        {!loading &&
          result != null &&
          result.kind === "text" &&
          result.text != null && (
            <pre className="font-family-mono text-xs text-ink p-3 whitespace-pre-wrap">
              {result.text}
            </pre>
          )}

        {!loading && result != null && result.kind === "binary" && (
          <EmptyState>Binary data · {formatSize(result.size)}</EmptyState>
        )}
      </div>
    </div>
  );
}
