// ui-svelte/src/components/HeadersDrawer.svelte
<script lang="ts">
  import type { ProxyHeaders } from "@bindings/ProxyHeaders";
  import SectionHeader from "./ui/SectionHeader.svelte";

  interface Props {
    requestHeaders?: ProxyHeaders;
    responseHeaders?: ProxyHeaders;
  }

  const { requestHeaders, responseHeaders }: Props = $props();

  let open = $state(false);

  const hasHeaders = $derived(
    (requestHeaders != null && requestHeaders.length > 0) ||
      (responseHeaders != null && responseHeaders.length > 0),
  );
</script>

{#if hasHeaders}
  <div class="border-t border-border shrink-0">
    <button
      onclick={() => {
        open = !open;
      }}
      class="w-full flex items-center gap-2 px-3 h-7 bg-bg2 hover:bg-bg3 transition-colors text-left"
      aria-expanded={open}
    >
      <SectionHeader>Headers</SectionHeader>
      <span class="text-dim text-xs">{open ? "▾" : "▸"}</span>
    </button>

    {#if open}
      <div class="px-3 py-2 bg-pane-bg overflow-auto max-h-56">
        {#if requestHeaders != null && requestHeaders.length > 0}
          <div class="mb-3">
            <div class="mb-1">
              <SectionHeader color="dim">Request</SectionHeader>
            </div>
            <table class="w-full text-xs font-family-mono">
              <tbody>
                {#each requestHeaders as h, i (i)}
                  <tr
                    class="border-b border-border last:border-0 hover:bg-hl-bg"
                  >
                    <td
                      class="py-0.5 pr-4 text-accent whitespace-nowrap align-top w-48"
                    >
                      {h.name}
                    </td>
                    <td class="py-0.5 text-ink break-all">{h.value}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}
        {#if responseHeaders != null && responseHeaders.length > 0}
          <div>
            <div class="mb-1">
              <SectionHeader color="dim">Response</SectionHeader>
            </div>
            <table class="w-full text-xs font-family-mono">
              <tbody>
                {#each responseHeaders as h, i (i)}
                  <tr
                    class="border-b border-border last:border-0 hover:bg-hl-bg"
                  >
                    <td
                      class="py-0.5 pr-4 text-accent whitespace-nowrap align-top w-48"
                    >
                      {h.name}
                    </td>
                    <td class="py-0.5 text-ink break-all">{h.value}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}
      </div>
    {/if}
  </div>
{/if}

// ui/src/components/HeadersDrawer.tsx
import { useState } from "react";
import type { ProxyHeaders } from "@bindings/ProxyHeaders";
import { SectionHeader } from "./ui/SectionHeader";

interface Props {
  requestHeaders?: ProxyHeaders;
  responseHeaders?: ProxyHeaders;
}

function HeaderTable({ headers }: { headers: ProxyHeaders }) {
  return (
    <table className="w-full text-xs font-family-mono">
      <tbody>
        {headers.map((h, i) => (
          <tr
            key={i}
            className="border-b border-border last:border-0 hover:bg-hl-bg"
          >
            <td className="py-0.5 pr-4 text-accent whitespace-nowrap align-top w-48">
              {h.name}
            </td>
            <td className="py-0.5 text-ink break-all">{h.value}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export function HeadersDrawer({ requestHeaders, responseHeaders }: Props) {
  const [open, setOpen] = useState(false);

  const hasHeaders =
    (requestHeaders != null && requestHeaders.length > 0) ||
    (responseHeaders != null && responseHeaders.length > 0);

  if (!hasHeaders) return null;

  return (
    <div className="border-t border-border shrink-0">
      {/* Toggle */}
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center gap-2 px-3 h-7 bg-bg2 hover:bg-bg3 transition-colors text-left"
        aria-expanded={open}
      >
        <SectionHeader>Headers</SectionHeader>
        <span className="text-dim text-xs">{open ? "▾" : "▸"}</span>
      </button>

      {/* Expanded content */}
      {open && (
        <div className="px-3 py-2 bg-pane-bg overflow-auto max-h-56">
          {requestHeaders != null && requestHeaders.length > 0 && (
            <div className="mb-3">
              <div className="mb-1">
                <SectionHeader color="dim">Request</SectionHeader>
              </div>
              <HeaderTable headers={requestHeaders} />
            </div>
          )}
          {responseHeaders != null && responseHeaders.length > 0 && (
            <div>
              <div className="mb-1">
                <SectionHeader color="dim">Response</SectionHeader>
              </div>
              <HeaderTable headers={responseHeaders} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
