// ui/src/components/ui/SectionHeader.tsx
interface Props {
  children: React.ReactNode;
  color?: "mid" | "dim";
}

export function SectionHeader({ children, color = "mid" }: Props) {
  return (
    <span
      className={`font-family-ui text-xs font-black uppercase tracking-widest ${color === "mid" ? "text-mid" : "text-dim"}`}
    >
      {children}
    </span>
  );
}

// ui-svelte/src/components/ui/SectionHeader.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    children: Snippet;
    color?: "mid" | "dim";
  }

  const { children, color = "mid" }: Props = $props();
</script>

<span
  class={`font-family-ui text-xs font-black uppercase tracking-widest ${color === "mid" ? "text-mid" : "text-dim"}`}
>
  {@render children()}
</span>
