// ui/src/components/ConnectionIndicator.tsx
import type { ConnectionStatus } from "@ui/api/sse";

interface Props {
  status: ConnectionStatus;
}

export function ConnectionIndicator({ status }: Props) {
  if (status === "connecting") {
    return (
      <span
        className="inline-block w-2 h-2 rounded-full bg-gold animate-pulse"
        title="Connecting"
      />
    );
  }
  if (status === "open") {
    return (
      <span
        className="inline-block w-2 h-2 rounded-full bg-green"
        title="Connected"
      />
    );
  }
  // reconnecting
  return (
    <span
      className="inline-block w-2 h-2 rounded-full bg-red animate-pulse"
      title="Reconnecting"
    />
  );
}

// ui-svelte/src/components/ConnectionIndicator.svelte
<script lang="ts">
  import type { ConnectionStatus } from "@ui/api/sse";

  interface Props {
    status: ConnectionStatus;
  }

  const { status }: Props = $props();
</script>

{#if status === "connecting"}
  <span
    class="inline-block w-2 h-2 rounded-full bg-gold animate-pulse"
    title="Connecting"
  ></span>
{:else if status === "open"}
  <span
    class="inline-block w-2 h-2 rounded-full bg-green"
    title="Connected"
  ></span>
{:else}
  <span
    class="inline-block w-2 h-2 rounded-full bg-red animate-pulse"
    title="Reconnecting"
  ></span>
{/if}
