// ui/src/components/ui/copy-button.tsx
import { useEffect, useRef, useState } from "react";
import { CheckIcon, CopyIcon } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@ui/components/ui/button";

interface CopyButtonProps {
  text?: string;
}

export function CopyButton({ text }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (timerRef.current != null) clearTimeout(timerRef.current);
    };
  }, []);

  async function handleClick() {
    if (text == null) return;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success("Copied to clipboard");
      if (timerRef.current != null) clearTimeout(timerRef.current);
      timerRef.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
      if (timerRef.current != null) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
      toast.error("Could not copy to clipboard");
    }
  }

  return (
    <Button
      type="button"
      variant="ghost"
      size="xs"
      onClick={handleClick}
      disabled={!text}
      aria-label={copied ? "Copied" : "Copy"}
      title={copied ? "Copied" : "Copy"}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
      <span>{copied ? "Copied" : "Copy"}</span>
    </Button>
  );
}

// ui-svelte/src/components/CopyButton.svelte
<script lang="ts">
  interface Props {
    text?: string;
  }

  const { text }: Props = $props();

  let copied = $state(false);
  let timer: ReturnType<typeof setTimeout> | null = null;

  function handleClick() {
    if (text == null) return;
    void navigator.clipboard.writeText(text);
    copied = true;
    if (timer != null) clearTimeout(timer);
    timer = setTimeout(() => {
      copied = false;
    }, 2000);
  }

  $effect(() => {
    return () => {
      if (timer != null) clearTimeout(timer);
    };
  });
</script>

<button
  onclick={handleClick}
  disabled={!text}
  class="font-family-mono text-xs text-accent hover:text-ink transition-colors cursor-pointer disabled:text-dim disabled:cursor-not-allowed disabled:opacity-50"
>
  {copied ? "Copied!" : "Copy"}
</button>
